using DientesLimpios.Aplicacion.CasosDeUso.Consultorios.Comandos.BorrarConsultorio;
using DientesLimpios.Aplicacion.Contratos.Persistencia;
using DientesLimpios.Aplicacion.Contratos.Repositorios;
using DientesLimpios.Aplicacion.Excepciones;
using DientesLimpios.Dominio.Entidades;
using NSubstitute;
using NSubstitute.ExceptionExtensions;
using NSubstitute.ReturnsExtensions;

namespace DientesLimpios.Pruebas.Aplicacion.CasosDeUso.Consultorios;

[TestClass]
public class CasoDeUsoBorrarConsultorioTests
{
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring as nullable.
    private IRepositorioConsultorios repositorio;
    private IUnidadDeTrabajo unidadDeTrabajo;
    private CasoDeUsoBorrarConsultorio casoDeUso;
#pragma warning restore CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring as nullable.

    [TestInitialize]
    public void Setup()
    {
        repositorio = Substitute.For<IRepositorioConsultorios>();
        unidadDeTrabajo = Substitute.For<IUnidadDeTrabajo>();
        casoDeUso = new CasoDeUsoBorrarConsultorio(repositorio, unidadDeTrabajo);
    }

    [TestMethod]
    public async Task Handle_CuandoConsultorioExiste_BorraConsultorioYPersiste()
    {
        var id = Guid.NewGuid();
        var comando = new ComandoBorrarConsultorio { Id = id };
        var consultorio = new Consultorio("Consultorio A");

        repositorio.ObtenerPorId(id).Returns(consultorio);

        await casoDeUso.Handle(comando);

        await repositorio.Received(1).Borrar(consultorio);
        await unidadDeTrabajo.Received(1).Persistir();

    }

    [TestMethod]
    public async Task Handle_CuandoConsultorioNoExiste_LanzaExcepcionNoEncontrado()
    {
        var comando = new ComandoBorrarConsultorio { Id = Guid.NewGuid() };
        repositorio.ObtenerPorId(comando.Id).ReturnsNull();

        await Assert.ThrowsExactlyAsync<ExcepcionNoEncontrado>(async () => await casoDeUso.Handle(comando));
    }

    [TestMethod]
    public async Task Handle_CuandoOcurreExcepcion_LlamaAReversarYLanzaExcepcion()
    {
        var id = Guid.NewGuid();
        var comando = new ComandoBorrarConsultorio { Id = id };
        var consultorio = new Consultorio("Consultorio A");

        repositorio.ObtenerPorId(id).Returns(consultorio);

        repositorio.Borrar(consultorio).Throws(new InvalidOperationException("Fallo al borrar"));

        await Assert.ThrowsExactlyAsync<InvalidOperationException>(() => casoDeUso.Handle(comando));
        await unidadDeTrabajo.Received(1).Reversar();
    }


}